name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
      - name: Publish
        run: dotnet publish --no-restore --no-build --verbosity normal -c Release
      - name: Pack
        run: dotnet pack --no-restore --no-build --verbosity normal -c Release
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: codeCoverage
          path: |
            src/Microsoft.Kiota.Cli.Commons.Tests/TestResults
      - name: Upload Nuget Package
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: |
            src/Microsoft.Kiota.Cli.Commons/bin/Release/*.nupkg
